site_name: <b>mbaLearnsToCode</b>
site_author: Vinh Luong (a.k.a. MBALearnsToCode)

include_nav: True
include_next_prev: False
pages:
  - <i class="fa fa-home"></i>: 'index.md'
  - <i class="fa fa-newspaper-o"></i> blogs:
    - <i class="fa fa-chevron-down"></i>: "blogs/_whats_in_here.md"
  - <i class="fa fa-check-square"></i> myRepertoire:
    - machineLearning_dataSci: 'myRepertoire/machineLearning_dataSci.md'
    - appDev: 'myRepertoire/_whats_in_here.md'
  - <i class="fa fa-book"></i> learningResources:
    - <i class="fa fa-chevron-down"></i>: 'learningResources/_whats_in_here.md'
    - chicagoBoothAnalyticsClub_learningResources: 'learningResources/chicagoBoothAnalyticsClub_learningResources.md'
  - <i class="fa fa-wrench"></i> <i class="fa fa-cogs"></i> toolRoom:
    - <i class="fa fa-chevron-down"></i>: 'toolRoom/_whats_in_here.md'
    - py: 'toolRoom/py.md'
    - pyDjango: 'toolRoom/pyDjango.md'
  - <i class="fa fa-pencil-square-o"></i> contactMe: 'contactMe.md'

# repo_url: 'https://github.com/MBALearnsToCode/MBALearnsToCode'

theme: mkdocs
extra_css: ['https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css',
            'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css',
            'https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css']

# math extension
# ref: https://github.com/mkdocs/mkdocs/issues/253
#markdown_extensions: [math]
#extra_javascript: ['https://code.jquery.com/jquery-2.1.3.min.js',
#                   # 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js',   # disabling this because it causes problems to the drop-downs
#                   'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML',
#                   'mathjaxhelper.js']
