site_name: <b>mbaLearnsToCode</b>
site_author: Vinh Luong (a.k.a. MBALearnsToCode)

include_nav: True
include_next_prev: False
pages:
  - <i class="fa fa-home"></i>: 'index.md'
  - <i class="fa fa-terminal"></i> myCodingRepertoire: 'myCodingRepertoire.md'
  - <i class="fa fa-newspaper-o"></i> myBlogs:
    - <i class="fa fa-chevron-down"></i>: "myBlogs/_myBlogs.md"
    - 2015-09-24 A Non-Traditional MBA's Mid-point Look-back: 'myBlogs/20150924_NonTraditionalMBAMidPointLookBack.md'
  - <i class="fa fa-book"></i> myLearningResources:
    - <i class="fa fa-chevron-down"></i>: 'myLearningResources/_myLearningResources.md'
    - Data Science Learning Resources by Chicago Booth Analytics Club: 'myLearningResources/chicagoBoothAnalyticsClub_learningResources.md'
  - <i class="fa fa-wrench"></i> <i class="fa fa-cogs"></i> myToolRoom:
    - <i class="fa fa-chevron-down"></i>: 'myToolRoom/_myToolRoom.md'
  - <i class="fa fa-info-circle"></i> contact(me): 'contactMe.md'

# repo_url: 'https://github.com/MBALearnsToCode/MBALearnsToCode'

theme: mkdocs
extra_css: ['https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css',
            'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css',
            'https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css',
            'styles.css']

# math extension
# ref: https://github.com/mkdocs/mkdocs/issues/253
markdown_extensions: [math]
extra_javascript: ['https://code.jquery.com/jquery-2.1.3.min.js',
                   # 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js',   # disabling this because it causes problems to the drop-downs
                   'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML',
                   'mathjaxhelper.js']
